# Home Manager module for niri-mapper
self:
{ config, lib, pkgs, ... }:

let
  cfg = config.services.niri-mapper;

  # Convert Nix attrset to KDL configuration
  configToKdl = config: let
    indent = level: lib.concatStrings (lib.genList (_: "    ") level);

    globalToKdl = global: ''
      global {
          log-level "${global.logLevel or "info"}"
          niri-keybinds-path "${global.niriKeybindsPath or "${config.xdg.configHome}/niri/niri-mapper-keybinds.kdl"}"
      }
    '';

    remapToKdl = level: remap:
      lib.concatStringsSep "\n" (lib.mapAttrsToList (from: to:
        "${indent level}${from} \"${to}\""
      ) remap);

    passthroughToKdl = level: passthrough:
      lib.concatStringsSep "\n" (map (bind:
        "${indent level}${bind.key} { ${bind.action} }"
      ) passthrough);

    profileToKdl = level: name: profile: ''
      ${indent level}profile "${name}" {
      ${lib.optionalString (profile.remap or {} != {}) ''
      ${indent (level + 1)}remap {
      ${remapToKdl (level + 2) profile.remap}
      ${indent (level + 1)}}
      ''}${lib.optionalString ((profile.niriPassthrough or []) != []) ''
      ${indent (level + 1)}niri-passthrough {
      ${passthroughToKdl (level + 2) profile.niriPassthrough}
      ${indent (level + 1)}}
      ''}${indent level}}
    '';

    deviceToKdl = device: ''
      device "${device.name}" {
      ${lib.concatStringsSep "\n" (lib.mapAttrsToList (profileToKdl 1) (device.profiles or { default = {}; }))}
      }
    '';
  in ''
    // Generated by Home Manager niri-mapper module
    ${globalToKdl (cfg.settings.global or {})}

    ${lib.concatStringsSep "\n" (map deviceToKdl (cfg.settings.devices or []))}
  '';
in
{
  options.services.niri-mapper = {
    enable = lib.mkEnableOption "niri-mapper input remapping daemon";

    package = lib.mkOption {
      type = lib.types.package;
      default = self.packages.${pkgs.system}.niri-mapper;
      description = "The niri-mapper package to use";
    };

    settings = lib.mkOption {
      type = lib.types.attrs;
      default = {};
      description = "niri-mapper configuration (will be converted to KDL)";
      example = lib.literalExpression ''
        {
          global = {
            logLevel = "info";
          };
          devices = [
            {
              name = "Keychron K3 Pro";
              profiles.default = {
                remap = {
                  CapsLock = "Escape";
                };
                niriPassthrough = [
                  { key = "Super+Return"; action = "spawn \"alacritty\";"; }
                ];
              };
            }
          ];
        }
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ cfg.package ];

    xdg.configFile."niri-mapper/config.kdl".text = configToKdl cfg.settings;

    systemd.user.services.niri-mapper = {
      Unit = {
        Description = "niri-mapper input remapping daemon";
        After = [ "graphical-session.target" ];
        PartOf = [ "graphical-session.target" ];
      };

      Service = {
        Type = "simple";
        ExecStart = "${cfg.package}/bin/niri-mapperd --config %h/.config/niri-mapper/config.kdl --foreground";
        Restart = "on-failure";
        RestartSec = 5;
      };

      Install = {
        WantedBy = [ "graphical-session.target" ];
      };
    };
  };
}
