# Home Manager module for niri-mapper
self:
{ config, lib, pkgs, ... }:

let
  cfg = config.services.niri-mapper;

  # Type definitions for niri-mapper configuration (mirrored from NixOS module)

  # Global settings submodule
  globalType = lib.types.submodule {
    options = {
      logLevel = lib.mkOption {
        type = lib.types.enum [ "trace" "debug" "info" "warn" "error" ];
        default = "info";
        description = "Log level for the niri-mapper daemon";
      };

      niriKeybindsPath = lib.mkOption {
        type = lib.types.str;
        default = "${config.xdg.configHome}/niri/niri-mapper-keybinds.kdl";
        description = "Path to write generated niri keybinds file";
      };
    };
  };

  # Niri passthrough binding submodule
  passthroughType = lib.types.submodule {
    options = {
      key = lib.mkOption {
        type = lib.types.str;
        description = "Key combination (e.g., 'Super+Return')";
        example = "Super+Return";
      };

      action = lib.mkOption {
        type = lib.types.str;
        description = "Niri action to execute (e.g., 'spawn \"alacritty\";')";
        example = ''spawn "alacritty";'';
      };
    };
  };

  # Profile submodule
  profileType = lib.types.submodule {
    options = {
      remap = lib.mkOption {
        type = lib.types.attrsOf lib.types.str;
        default = {};
        description = "Key remappings (from -> to)";
        example = lib.literalExpression ''
          {
            CapsLock = "Escape";
            Escape = "CapsLock";
          }
        '';
      };

      niriPassthrough = lib.mkOption {
        type = lib.types.listOf passthroughType;
        default = [];
        description = "Keybinds to pass through to niri";
        example = lib.literalExpression ''
          [
            { key = "Super+Return"; action = "spawn \"alacritty\";"; }
          ]
        '';
      };

      combo = lib.mkOption {
        type = lib.types.attrsOf lib.types.str;
        default = {};
        description = "Key combination remappings (e.g., Ctrl+Shift+Q -> Alt+F4)";
        example = lib.literalExpression ''
          {
            "Ctrl+Shift+Q" = "Alt+F4";
          }
        '';
      };
    };
  };

  # Device submodule
  deviceType = lib.types.submodule {
    options = {
      name = lib.mkOption {
        type = lib.types.str;
        description = "Device name to match (exact match)";
        example = "Keychron K3 Pro";
      };

      profiles = lib.mkOption {
        type = lib.types.attrsOf profileType;
        default = { default = {}; };
        description = "Named profiles for this device";
        example = lib.literalExpression ''
          {
            default = {
              remap = { CapsLock = "Escape"; };
            };
          }
        '';
      };
    };
  };

  # Settings submodule (top-level)
  settingsType = lib.types.submodule {
    options = {
      global = lib.mkOption {
        type = globalType;
        default = {};
        description = "Global settings for niri-mapper";
      };

      devices = lib.mkOption {
        type = lib.types.listOf deviceType;
        default = [];
        description = "List of devices to configure";
      };
    };
  };

  # Convert Nix attrset to KDL configuration
  configToKdl = settings: let
    indent = level: lib.concatStrings (lib.genList (_: "    ") level);

    globalToKdl = global: ''
      global {
          log-level "${global.logLevel or "info"}"
          niri-keybinds-path "${global.niriKeybindsPath or "${config.xdg.configHome}/niri/niri-mapper-keybinds.kdl"}"
      }
    '';

    remapToKdl = level: remap:
      lib.concatStringsSep "\n" (lib.mapAttrsToList (from: to:
        "${indent level}${from} \"${to}\""
      ) remap);

    passthroughToKdl = level: passthrough:
      lib.concatStringsSep "\n" (map (bind:
        "${indent level}${bind.key} { ${bind.action} }"
      ) passthrough);

    profileToKdl = level: name: profile: ''
      ${indent level}profile "${name}" {
      ${lib.optionalString (profile.remap or {} != {}) ''
      ${indent (level + 1)}remap {
      ${remapToKdl (level + 2) profile.remap}
      ${indent (level + 1)}}
      ''}${lib.optionalString ((profile.niriPassthrough or []) != []) ''
      ${indent (level + 1)}niri-passthrough {
      ${passthroughToKdl (level + 2) profile.niriPassthrough}
      ${indent (level + 1)}}
      ''}${indent level}}
    '';

    deviceToKdl = device: ''
      device "${device.name}" {
      ${lib.concatStringsSep "\n" (lib.mapAttrsToList (profileToKdl 1) (device.profiles or { default = {}; }))}
      }
    '';
  in ''
    // Generated by Home Manager niri-mapper module
    ${globalToKdl (cfg.settings.global or {})}

    ${lib.concatStringsSep "\n" (map deviceToKdl (cfg.settings.devices or []))}
  '';
in
{
  options.services.niri-mapper = {
    enable = lib.mkEnableOption "niri-mapper input remapping daemon";

    package = lib.mkOption {
      type = lib.types.package;
      default = self.packages.${pkgs.system}.niri-mapper;
      description = "The niri-mapper package to use";
    };

    settings = lib.mkOption {
      type = settingsType;
      default = {};
      description = "niri-mapper configuration (will be converted to KDL)";
      example = lib.literalExpression ''
        {
          global = {
            logLevel = "info";
            # Uses XDG config home by default
            # niriKeybindsPath = "~/.config/niri/niri-mapper-keybinds.kdl";
          };
          devices = [
            {
              name = "Keychron K3 Pro";
              profiles.default = {
                remap = {
                  CapsLock = "Escape";
                  Escape = "CapsLock";
                };
                niriPassthrough = [
                  { key = "Super+Return"; action = "spawn \"alacritty\";"; }
                  { key = "Super+d"; action = "spawn \"fuzzel\";"; }
                ];
                combo = {
                  "Ctrl+Shift+Q" = "Alt+F4";
                };
              };
            }
          ];
        }
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ cfg.package ];

    xdg.configFile."niri-mapper/config.kdl".text = configToKdl cfg.settings;

    systemd.user.services.niri-mapper = {
      Unit = {
        Description = "niri-mapper input remapping daemon";
        After = [ "graphical-session.target" ];
        PartOf = [ "graphical-session.target" ];
      };

      Service = {
        Type = "simple";
        ExecStart = "${cfg.package}/bin/niri-mapperd --config %h/.config/niri-mapper/config.kdl --foreground";
        Restart = "on-failure";
        RestartSec = 5;
      };

      Install = {
        WantedBy = [ "graphical-session.target" ];
      };
    };
  };
}
