# NixOS module for niri-mapper
self:
{ config, lib, pkgs, ... }:

let
  cfg = config.services.niri-mapper;

  # Convert Nix attrset to KDL configuration
  configToKdl = config: let
    indent = level: lib.concatStrings (lib.genList (_: "    ") level);

    globalToKdl = global: ''
      global {
          log-level "${global.logLevel or "info"}"
          niri-keybinds-path "${global.niriKeybindsPath or "~/.config/niri/niri-mapper-keybinds.kdl"}"
      }
    '';

    remapToKdl = level: remap:
      lib.concatStringsSep "\n" (lib.mapAttrsToList (from: to:
        "${indent level}${from} \"${to}\""
      ) remap);

    passthroughToKdl = level: passthrough:
      lib.concatStringsSep "\n" (map (bind:
        "${indent level}${bind.key} { ${bind.action} }"
      ) passthrough);

    profileToKdl = level: name: profile: ''
      ${indent level}profile "${name}" {
      ${lib.optionalString (profile.remap or {} != {}) ''
      ${indent (level + 1)}remap {
      ${remapToKdl (level + 2) profile.remap}
      ${indent (level + 1)}}
      ''}${lib.optionalString ((profile.niriPassthrough or []) != []) ''
      ${indent (level + 1)}niri-passthrough {
      ${passthroughToKdl (level + 2) profile.niriPassthrough}
      ${indent (level + 1)}}
      ''}${indent level}}
    '';

    deviceToKdl = device: ''
      device "${device.name}" {
      ${lib.concatStringsSep "\n" (lib.mapAttrsToList (profileToKdl 1) (device.profiles or { default = {}; }))}
      }
    '';
  in ''
    // Generated by NixOS niri-mapper module
    ${globalToKdl (config.global or {})}

    ${lib.concatStringsSep "\n" (map deviceToKdl (config.devices or []))}
  '';

  configFile = pkgs.writeText "niri-mapper-config.kdl" (configToKdl cfg.settings);
in
{
  options.services.niri-mapper = {
    enable = lib.mkEnableOption "niri-mapper input remapping daemon";

    package = lib.mkOption {
      type = lib.types.package;
      default = self.packages.${pkgs.system}.niri-mapper;
      description = "The niri-mapper package to use";
    };

    settings = lib.mkOption {
      type = lib.types.attrs;
      default = {};
      description = "niri-mapper configuration (will be converted to KDL)";
      example = lib.literalExpression ''
        {
          global = {
            logLevel = "info";
            niriKeybindsPath = "~/.config/niri/niri-mapper-keybinds.kdl";
          };
          devices = [
            {
              name = "Keychron K3 Pro";
              profiles.default = {
                remap = {
                  CapsLock = "Escape";
                  Escape = "CapsLock";
                };
                niriPassthrough = [
                  { key = "Super+Return"; action = "spawn \"alacritty\";"; }
                  { key = "Super+d"; action = "spawn \"fuzzel\";"; }
                ];
              };
            }
          ];
        }
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ cfg.package ];

    systemd.services.niri-mapper = {
      description = "niri-mapper input remapping daemon";
      wantedBy = [ "graphical-session.target" ];
      after = [ "graphical-session.target" ];

      serviceConfig = {
        Type = "simple";
        ExecStart = "${cfg.package}/bin/niri-mapperd --config ${configFile} --foreground";
        Restart = "on-failure";
        RestartSec = 5;

        # Security hardening
        NoNewPrivileges = false;  # Needs privileges for uinput
        ProtectSystem = "strict";
        ProtectHome = "read-only";
        PrivateTmp = true;

        # Required for input device access
        SupplementaryGroups = [ "input" ];
      };
    };

    # Ensure uinput module is loaded
    boot.kernelModules = [ "uinput" ];

    # udev rules for input device access
    services.udev.extraRules = ''
      # niri-mapper: allow access to uinput
      KERNEL=="uinput", MODE="0660", GROUP="input", OPTIONS+="static_node=uinput"
    '';
  };
}
