//! Generate niri-compatible KDL keybind files

use crate::model::Config;
use crate::error::ConfigError;

/// Generate niri keybinds KDL from the configuration
pub fn generate_niri_keybinds(config: &Config) -> String {
    let mut output = String::new();

    output.push_str("// Auto-generated by niri-mapper - DO NOT EDIT\n");
    output.push_str("// Source: niri-mapper config\n");
    output.push_str("// Include this in your niri config.kdl:\n");
    output.push_str(&format!(
        "//   include \"{}\"\n\n",
        config.global.niri_keybinds_path.display()
    ));

    output.push_str("binds {\n");

    // Collect all niri-passthrough keybinds from all devices/profiles
    for device in &config.devices {
        for (_profile_name, profile) in &device.profiles {
            for keybind in &profile.niri_passthrough {
                // Convert Super to Mod for niri
                let niri_key = keybind.key.replace("Super", "Mod");
                output.push_str(&format!("    {} {{ {} }}\n", niri_key, keybind.action));
            }
        }
    }

    output.push_str("}\n");

    output
}

/// Write niri keybinds to the configured path
pub fn write_niri_keybinds(config: &Config) -> Result<(), ConfigError> {
    let content = generate_niri_keybinds(config);
    let path = &config.global.niri_keybinds_path;

    // Ensure parent directory exists
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    std::fs::write(path, content)?;
    tracing::info!("Wrote niri keybinds to {}", path.display());

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::*;

    #[test]
    fn test_generate_keybinds() {
        let config = Config {
            global: GlobalConfig::default(),
            devices: vec![DeviceConfig {
                name: Some("Test".to_string()),
                vendor_product: None,
                profiles: [("default".to_string(), Profile {
                    niri_passthrough: vec![
                        NiriKeybind {
                            key: "Super+Return".to_string(),
                            action: "spawn \"alacritty\";".to_string(),
                        },
                    ],
                    ..Default::default()
                })].into_iter().collect(),
            }],
        };

        let output = generate_niri_keybinds(&config);
        assert!(output.contains("Mod+Return"));
        assert!(output.contains("spawn \"alacritty\""));
    }
}
